---
title: "Examen de Cálculo, GITI + GITT, ICAI."
output:
  slidy_presentation: 
    includes:
      in_header: startTime.html
    self-contained: yes
  ioslides_presentation:
    includes:
      in_header: startTime.html
    self-contained: yes
date: 'Lunes 4 de Mayo de 2026, 11:30-14:30'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

---

### Examen de Cálculo, GITI + GITT, ICAI  (2026-05-04, 11:30).

<h1><div id="txt1"></div></h1>

<h1 style="color:red">Dispositivos electrónicos.</h1>

<div style="font-weight:600;color:red;font-size:150%">

+ No se permite ningún dispositivo electrónico. Móviles, portátiles, tablets, relojes, auriculares han de estar apagados, guardados en la mochila y la mochila debajo de la silla.

+ Si tienes algún dispositivo que no se puede apagar comunícaselo al profesor y déjalo en tu bolsa en la parte delantera del aula, lejos de tu puesto.

</div>

---

### Examen de Cálculo, GITI + GITT, ICAI  (2026-05-04, 11:30).

<h1>Instrucciones para el examen.</h1>

<h1><div id="txt2"></div></h1>

 + Todos los dispositivos electrónicos deben estar apagados y guardados. 
 + El examen tendrá una duración de **3 horas (hasta las 14:30)**.
 + No se puede utilizar calculadora.
 + El examen debe hacerse con bolígrafo.
 + No se puede abandonar el aula durante el examen. 
 
 

---

### Examen de Cálculo, GITI + GITT, ICAI  (2026-05-04, 11:30).
 
<h1> Instrucciones de entrega del examen.</h1>

<h1><div id="txt3"></div></h1>

 + Una vez finalizado el examen dispondrás de 5 minutos para  <span style = "color:red"> **escanear con el móvil en un único documento pdf: la portada con tu nombre y el desarrollo del examen ordenado.**</span> 
 + <span style = "color:red">**No hace falta escanear la Hoja Resumen ni el dorso de los enunciados.**</span>
 + **Nombre del documento escaneado para subir a Moodle:** <span style = "color:red">**Apellido1_Apellido2_Nombre.pdf**</span>
 + Debes subir el examen escaneado a la <span style = "color:red">**tarea de Moodle correspondiente**</span>
    + **Entrega EXAMEN FINAL de Cálculo - 4 de mayo de 2026**  
    + **Entrega 2º EXAMEN PARCIAL de Cálculo - 4 de mayo de 2026**  
    Busca *Entrega de exámenes y pruebas* en la columna de la izquierda).
 + Si tienes problemas para subir el documento escaneado a Moodle, envíalo por correo electrónico a tu profesor lo antes posible. 
 + Antes de abandonar el aula <span style = "color:red">**entrega la portada con tu nombre en el sitio indicado y el examen en papel**</span> al profesor para graparlo **pero NO la Hoja Resumen**.
 
 
 
<!-- ##################################################################################################################### --> 
<!-- ##################################################################################################################### --> 
<!-- ##################################################################################################################### --> 

